---
title: "R Learning Project"
author: "Alan Thomas Joshy"
date: "2026-03-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The following is my first vector in this learning project, a set of hypothetical temperature readings from hypothetical reef survey sites
```{r}
temp <- c(24.5,27.1,22.8,26.3,29.0)
temp
```

##Loading and inspecting a dataset:
```{r}
data("airquality")
head(airquality)

```

##Exploring the Structure:
```{r}
str(airquality)
```

##Summary Statistics:
```{r}
summary(airquality)
```

```{r}
mean(airquality$Ozone) #gies the output of NA because of the presence of missing values/NAs

mean(airquality$Ozone, na.rm = TRUE) # this gives mean result because we tell R to ingnore the NAs

colSums(is.na(airquality)) #colSums(is.na()) can be used to get an idea of the NAs in the dataframe

```

##Basic Arithmetic andvariable manipulation:
```{r}
10+5
10-5
10*5
10/5
10^2
10%%2
10%%3
```

```{r}
#working with a Numeric Variable
depth <- 15
depth_feet <- depth * 3.281
depth
depth_feet

#Updating varibale
depth <- depth+15      #depth is now 30
depth
```

R can let us modify a whole vector instead of having to loop, eg
```{r}
Temperature_C <- c(25,26,27,28,28)
Temperature_f <- Temperature_C +32
Temperature_f   # all the values of the vector is converted to farhenheit, which can be very useful wehen working with large datasets...

```


